### ISSUE TITLE
Immutability: analyzer assumes initializers are the only writes to readonly members

### ISSUE THREAD

**Issue by j3parker** [Brightspace/D2L.CodeStyle#319]
When the mutability analyzer sees an initializer for a field/property it assumes that its safe to inspect the (possibly narrower) type of the initializer rather than the type of field/property.

However there may be writes to the field/property after the initializer if there are constructors. An example:

```cs
public interface IFoo {}

[Immutable]
public sealed class Good : IFoo {}

public class Bad : IFoo { public int x; }

[Immutable]
public sealed Bar {
    public readonly IFoo m_foo = new Good();

    public Bar() {
        m_foo = new Bad(); // happens after the field initializer, not seen by the analyzer
    }
}
```

The analyzer judges `Bar` to be immutable because `Bar` is `sealed`, has an immutable base-class (`System.object`) and it's only field/property `Bar.m_foo` has an initializer of type `Good` which is immutable. However, the constructor overwrites `m_foo` with something of type `Bad` after the initializer...

We need to consider other writes to `m_foo`. Judging by the spec (mostly [here](https://github.com/dotnet/csharplang/blob/master/spec/classes.md#readonly-fields)) we can get away with finding each constructor and checking for these sorts of syntax:

1. `AssignmentExpressionSyntax`: use the same logic as initializers for the RHS expr.
2. `ArgumentSyntax` with `RefKindKeyword` of `SyntaxKind.OutKeyword` (`out` parameters): narrow to the type of the corresponding parameter.
3. `ArgumentSyntax` with `RefKindKeyword` of `SyntaxKind.RefKeyword` (`ref` parameters): narrow to the type of the corresponding parameter.

We could inspect each write independently and combine the results pessimistically (if any write introduces potential immutability, judge the member as mutable.)

We could do something fancier where we order the writes and determine that a particular write has to happen before another write (i.e. the field always gets overwritten) but I don't think that's likely to ever be helpful in practice so I don't think it's worth the trouble.

This was found while doing #318: since we're using the mutability inspector a *tiny* bit more it changed the behaviour enough that the unnecessary annotations diagnostic for static variables triggered for code like this:

```cs
public class Foo {
    [Statics.Unaudited( Because.ItsStickyDataOhNooo )]
    public static readonly IEvilThing m_evil = null;

    public static Foo() {
        m_evil = new ActualEvil();
    }
}
```

The analyzer saw the `null` initializer and was like "damn, that's safe" and started complaining about the `Statics.Unaudited`, saying it was unnecessary.

**Comment by j3parker** [comment]
Regarding the last bit, ironically I handled `null` specifically but was skeptical it was going to be used (probably should have checked): https://github.com/Brightspace/D2L.CodeStyle/blob/cefba0f949309499b708c3084437ed48b9a15173/src/D2L.CodeStyle.Analyzers/Immutability/MutabilityInspector.cs#L379-L383

**Comment by TimothyJCowen** [comment]
Closed by https://github.com/Brightspace/D2L.CodeStyle/pull/698
