### ISSUE TITLE
Structs should only be analyzed as immutable when they are readonly

### ISSUE THREAD

**Issue by j3parker** [Brightspace/D2L.CodeStyle#463]
This code passes analysis:

```cs
using System;

[Immutable]
public struct Foo {
    public Foo(int value) {
      Value = value;
    }
    
    public int Value { get; }
    
    public void EvilReplace( Foo foo ) {
      this = foo;
    }
}

public static class Program {
    // m_foo must be [Immutable] because it's static
    private static Foo m_foo = new Foo( 3 );
    
    public static void Main() {
        Console.WriteLine( "before: " + m_foo.Value );
        m_foo.EvilReplace( new Foo( 7 ) );
        Console.WriteLine( "after: " + m_foo.Value );
    }
}
```

But it outputs:

```
before: 3
after: 7
```

C# 7 added [`readonly struct`s](https://github.com/dotnet/csharplang/blob/master/proposals/csharp-7.2/readonly-ref.md#readonly-structs) which will block stomping `this` outside the constructor. We should make the analyzer require `struct`s to be `readonly` when they are `[Immutable]`.

It sounds like we might have to do something a bit nasty to plug the hole: https://github.com/dotnet/roslyn/issues/23792 indicates there may not be good public APIs for getting this info.

**Comment by j3parker** [comment]
Ok, I'm actually not sure that this is a problem.

In the example above, the first complaint will actually be that the *field*  `m_foo` should be `readonly` first (before being `[Immutable]`) which, if true, means accesses like the call to `m_foo.EvilReplace` will operate on either [a copy](https://codeblog.jonskeet.uk/2014/07/16/micro-optimization-the-surprising-inefficiency-of-readonly-fields/) or if the `struct` is `readonly` not a copy, but then `EvilReplace` won't work... but in no case does `EvilReplace` actually hurt us.

Make sense @omsmith ?

Requiring that all `[Immutable]` `struct`s be `readonly` for performance seems reasonable to me, though. That could be a separate thing.

**Comment by omsmith** [comment]
So it would only come up if it's a non-static non-readonly field of a not-immutable type.

Certainly still surprising, but matters less from a correctness standpoint for sure.
