### ISSUE TITLE
Add an [Immutable] attribute, to make sure 100000 diagnostics don't pop up when a type goes from Immutable -> Mutable. 

### ISSUE THREAD

**Issue by saquibmian** [Brightspace/D2L.CodeStyle#5]
We should add an `[Immutable]` attribute, to make sure 100000 diagnostics don't pop up when a type goes from Immutable -> Mutable and lots of people are using it. 

So `UnsafeStaticsAnalyzer` will not validate immutability of types marked `[Immutable]`, but `ImmutabilityAnalyzer` will throw a single diagnostic when that type is marked `[Immutable]` but actually isn't. If someone removes the `[Immutable]` attribute, _then_ we'll get 100000 diagnostics, which is completely fine. 

This also gives us better runtime performance via annotated caching (only inspect a type for immutability once).

**Comment by j3parker** [comment]
I think we should probably use `[Pure]` from `System.Diagnostics.Contracts`.
