### ISSUE TITLE
Prevent losing Exception context on rethrow

### ISSUE THREAD

**Issue by mthjones** [Brightspace/D2L.CodeStyle#515]
## Problem
When exceptions are rethrown from `catch` blocks, there are two typical ways:

#### Option 1
```csharp
try {
    // do work
} catch( Exception e ) {
    // log, etc.
    throw e;
}
```

#### Option 2
```csharp
try {
    // do work
} catch( Exception ) {
    // log, etc.
    throw;
}
```

The problem is that Option 1 will lose all stacktrace context when rethrowing the exception, making it difficult to track down issues in the code if those errors do happen, while Option 2 retains the complete original exception context.

## Analyzer
I propose adding a new analyzer that looks for uses of Option 1 in the code and suggests switching them to Option 2. To make it simple, it could look for cases where the caught exception variable is rethrown and without being re-assigned in the `catch` block.

### Example
```csharp
try {
    // do work
} catch( Exception e ) {
    // log, etc.
    // D2LXXXX: This exception rethrow will lose all stacktrace context of the original exception.
    // Replace with `throw;` to rethrow the original exception with the complete stacktrace.
    throw e;
}
```

## Additional Considerations
There are potentially cases where the exception is instead captured into a variable that's rethrown outside of the `catch` block, or it's desired to rethrow an existing exception from elsewhere (e.g. unwrapping an exception's `InnerException`). These scenarios can be handled by using `ExceptionDispatchInfo.Capture( e )`, but these scenarios may be much more difficult to create an analyzer for.

**Comment by omsmith** [comment]
I was bored and whipped together a start to this in https://github.com/Brightspace/D2L.CodeStyle/pull/542. Anyone can feel free to bring it over the line.
