### ISSUE TITLE
Assess recent C# features wrt mutability analyzer

### ISSUE THREAD

**Issue by j3parker** [Brightspace/D2L.CodeStyle#582]
Off the top of my head we probably don't deal with record types well.

I think the analyzer has long-standing trouble with `ValueTuple` syntax (e.g. `(int, string)`) -- we should add some spec tests there

**Comment by omsmith** [comment]
> I think the analyzer has long-standing trouble with ValueTuple syntax (e.g. (int, string)) -- we should add some spec tests there

Nah, ValueTuple should already be working in the existing analyzers. https://github.com/Brightspace/D2L.CodeStyle/pull/507

**Comment by j3parker** [comment]
I'll do a quick audit of the changelogs, but records were the big one.
Went from C# 7.3 -> 9.0.

**Comment by j3parker** [comment]
* Mark these types immutable:
  * System.Index
  * System.Range
* [Wider support for init-only setters](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-9#init-only-setters)
* Test cases for:
  * Target-typed new: `Foo x = new();`

**Comment by j3parker** [comment]
@omsmith could you double check C# 7.2 - 9.0 and see if anything else looks relevant?
https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-9

**Comment by j3parker** [comment]
He looked. Theres maybe some stuff for the stateless func stuff but o/w we look good.
