### ISSUE TITLE
More uniform way to annotate external types

### ISSUE THREAD

**Issue by j3parker** [Brightspace/D2L.CodeStyle#585]
There should be one way (ignoring the special built-in types) to annotate external types like `ImmutableArray<T>`. See #583 as a dependency of this.

It should be via a config file that gets passed to the analyzer by the project.

In the LMS monorepo we can have one repo-wide config that we use.

Right now we treat `IEnumerable<T>` as an immutable container type which is weird (e.g. `List<T>` is definitely not immutable)... that might make sense for our code-base but we don't need to bake it into the analyzer.

**Comment by omsmith** [comment]
I think there's benefit of having actually-properly immutable things baked into the analyzer as to not re-do work.

Having `IEnumerable<T>` is weird yeah, and is unfortunate, but if it's needed for the LMS.

There's good and bad about it being configurable, and good and bad about it being not. Most of them come from the analyzer being used in different places.

I would worry about desync between the monorepo and something like `D2L.Core`, where things start falling apart given one relies on analysis done during compilation of the other.

**Comment by j3parker** [comment]
What re-work?

All of the non-closed types we encode like `count4net.IValueCounter` and `System.Web.UI.PageHandlerFactory` share a similar (but less obvious) problem as `IEnumerable<T>`: we can't guarantee that we analyze all implementations of `PageHandlerFactory`, so baking it into the analyzer is a pretty strong opinion. It makes sense for us, but I don't think it needs to be baked in.

> I would worry about desync between the monorepo and something like D2L.Core, where things start falling apart given one relies on analysis done during compilation of the other.

How would that happen? If D2L.Core didn't bless any types this wouldn't cause any problem as far as I know. When analyzing a dependency of D2L.Core we only care about which types defined in D2L.Core have `[Immutable]`, not what the contents of their types are (in general we can't even really ask what the contents are, that's why we restrict ourselves to analyzing a DLL at a time).

**Comment by omsmith** [comment]
> What re-work?

Re-work such as listing "obviously" immutable things like `ImmutableArray<T>`.

> If D2L.Core didn't bless any types this wouldn't cause any problem as far as I know.

I meant more-so if it say, erroneously listed `ImmutableArray<T>.Builder` as being immutable. Different lists can be pretty similar to having different versions of the analyzer, making different guarantees. Not a problem as long as entries are actually thought out and well intentioned - so probably not a problem in D2L.Core given the owners. It's just potentially equivalent to slapping audited and a bunch of bad stuff, except it doesn't _keep_ showing up so is harder to notice.

Anyway, good and bad. Having it be configured means a library like D2L.Core doesn't need to inherit bad exceptions, which is good.

**Comment by j3parker** [comment]
I can buy `ImmutableArray<T>` being in an official/default list, but I think it should be specified "in the same way" as all the other exceptions. Mostly what I'm getting at here is that we have/historically have had multiple ways of blessing things:

* Container types: https://github.com/Brightspace/D2L.CodeStyle/blob/master/src/D2L.CodeStyle.Analyzers/Immutability/ImmutableContainerMethods.cs#L7
* Non-container types: https://github.com/Brightspace/D2L.CodeStyle/blob/master/src/D2L.CodeStyle.Analyzers/Immutability/KnownImmutableTypes.cs#L11
* Looks like I already got rid of the third way I remembered: https://github.com/Brightspace/D2L.CodeStyle/pull/414

Which is unnecessary - there can be one uniform way. I can buy shipping a default list (that you could opt-out of, but why would you?) that contains stuff like `ImmutableArray<T>`. Along the same lines as [`-noconfig`](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/noconfig-compiler-option) in `csc.exe`. But I think they should all feed into the same uniform system rather than having different code for container types vs. non container types (this is about making the analyzer more general; a non-container type is just an immutable type with no `[Immutable]` generic params, it should be the same code).

> I meant more-so if it say, erroneously listed ImmutableArray<T>.Builder as being immutable. Different lists can be pretty similar to having different versions of the analyzer, making different guarantees. Not a problem as long as entries are actually thought out and well intentioned - so probably not a problem in D2L.Core given the owners. It's just potentially equivalent to slapping audited and a bunch of bad stuff, except it doesn't keep showing up so is harder to notice.

There's risk to this, for sure. We used to have `Types.Audited` which let you add things on a per-assembly basis but that was hard to wrangle in the mono-repo (which is why I removed it; I forgot that I already did that!). Having it be an analyzer config file would allow us to share the file across the LMS which is a lot easier to wrangle.

The fact is that right now we have some wrong opinions baked into the analyzer like `ImmutableArray<T>.Builder`. I don't think we need this, we can hide those horrors in the LMS. It's a lot easier to burn that list down if its in the LMS vs. hard-coded.

**Comment by omsmith** [comment]
>  can buy shipping a default list (that you could opt-out of, but why would you?) that contains stuff like ImmutableArray<T>

Yeah, that's all I'm hoping for!

**Comment by j3parker** [comment]
ImmutabilityContext captures what I meant by this -- done!
