### ISSUE TITLE
[Constant] analyzer could take into account a symbol's [Constant]-ness

### ISSUE THREAD

**Issue by j3parker** [Brightspace/D2L.CodeStyle#704]
@TimothyJCowen reports:

```cs
public void Foo( [Constant]string x ) {
  Bar( x, null );
}

public void Bar( [Constant]string x, object y ) {
  // ...
}
```

At the call for `Bar( ... )` there is a diagnostic because `x` is not constant.

Naively, we could notice that `x` is an identifier, find the associated symbol and notice it has the `[Constant]` attribute. This comes up a bunch in the logging code.

This would allow for this, though:

```cs
public void Foo( [Constant]string x ) {
  x = SomeVeryDynamicFunction();
  Bar( x, null );
}
```

This should, ideally, ignore the `[Constant]` on x's decl because it is overwritten.

I think this is a bit of a rabbit hole to go down. We're lucky that the only constant types are value types, so we would only need to look for assignments, outs, refs, etc. (rather than it simply being passed like normal to other functions). Technically we could go further and look at assignments to see if they were also compile time, etc.

I can possibly see this being worth it, e.g. for SQL injection stuff, but I think we should proceed slowly.
It may be sane to implement the naive thing first and work towards filling the holes. We should think about this carefully before jumping in.

**Comment by TimothyJCowen** [comment]
> This should, ideally, ignore the [Constant] on x's decl because it is overwritten.
The way I was thinking of it was that the `x = SomeVeryDynamicFunction();` wouldn't even be allowed. The analyzer would say that because `x` is `[Constant]` it cannot be written to.

**Comment by j3parker** [comment]
Yep, that's possible too.

**Comment by omsmith** [comment]
>   x = SomeVeryDynamicFunction();

This will prevent that pretty simply (given existing analyzer things):

```diff
-	public sealed class ConstantAttribute : Attribute {
+	public sealed class ConstantAttribute : ReadOnlyAttribute {
	}
```

The exact same "inheritance" is done for StatelessFunc, and read-only was implemented for the same reason.

https://github.com/Brightspace/D2L.CodeStyle/blob/11739f8c8495bf95b05368f0b48fe5d53833163f/src/D2L.CodeStyle.Analyzers/Immutability/StatelessFuncAnalyzer.cs#L145-L191

**Comment by omsmith** [comment]
And the ReadOnlyAnalyzer: https://github.com/Brightspace/D2L.CodeStyle/blob/11739f8c8495bf95b05368f0b48fe5d53833163f/src/D2L.CodeStyle.Analyzers/Immutability/ReadOnlyParameterAnalyzer.cs#L43

**Comment by TimothyJCowen** [comment]
Well darn, that's perfect. Thanks Owen!

**Comment by TimothyJCowen** [comment]
Another option is [here](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-7.2/readonly-ref#solution-in-parameters), just for reference.

**Comment by j3parker** [comment]
Nice!

**Comment by omsmith** [comment]
`in` would also probably work for the purposes of constant analyzer, given the initial value had to have been constant 👍
